title: Dr. Tobias Pielok
description: Statistics, variational inference, and AI education
url: "https://tpielok.github.io"
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
permalink: /:categories/:title/
header_pages:
  - about.md
  - updates.md
github_username: tpielok
